use anyhow::Result;

use crate::tui::events::TuiEvent;
use crate::workflows::{RunOptions, send_agent_progress, send_agent_summary};

const PREAMBLE: &str = r#"You are a strategic planning agent for Cortex, an AI-powered software development system.

Your role is to analyze a user's idea and produce a comprehensive implementation plan BEFORE any development begins.

Given a software idea, you must:

1. **Identify ambiguities** — List 2-3 specific questions that, if answered, would significantly affect implementation decisions (language, architecture, scope, etc.). Format them as:
   QUESTIONS:
   - Q1: [question]
   - Q2: [question]
   - Q3: [question]

2. **Produce a PLAN** — After the questions section, write a detailed plan with the following sections:
   PLAN:
   ## Summary
   [1-2 sentence description of what will be built]

   ## Tech Stack
   [Language, framework, key libraries]

   ## Agent Execution Plan
   - **CEO**: [what brief they will produce]
   - **PM**: [what specs.md will contain, estimated features]
   - **Tech Lead**: [architecture decisions, patterns]
   - **Developer**: [key files to create, estimated count]
   - **QA**: [what tests will cover]
   - **DevOps**: [deployment config]

   ## Expected Outputs
   [List of files that will be created]

   ## Risks & Assumptions
   [2-3 key risks or assumptions]

If existing context (AGENTS.md, specs.md) is provided, incorporate it into your plan.
Keep the QUESTIONS section brief — only ask what's genuinely ambiguous.
If the idea is completely clear, you may output 0 questions.
"#;

pub async fn run(idea: &str, opts: &RunOptions) -> Result<()> {
    let _ = opts.tx.send(TuiEvent::AgentStarted {
        agent: "planner".into(),
    });
    send_agent_progress(opts, "planner", "Scanning project and preparing plan…");

    // Gather existing context from the project directory if available.
    let mut context_sections = Vec::new();

    let agents_md_path = opts.project_dir.join("AGENTS.md");
    if let Ok(content) = std::fs::read_to_string(&agents_md_path) {
        context_sections.push(format!("## Existing AGENTS.md\n{}", content));
    }

    let specs_md_path = opts.project_dir.join("specs.md");
    if let Ok(content) = std::fs::read_to_string(&specs_md_path) {
        context_sections.push(format!("## Existing specs.md\n{}", content));
    }

    let context_block = if context_sections.is_empty() {
        String::new()
    } else {
        format!(
            "\n\n## Existing Project Context\n{}\n",
            context_sections.join("\n\n")
        )
    };

    let prompt = format!(
        "Idea: {}{}\n\nProduce the QUESTIONS and PLAN sections as instructed.",
        idea, context_block
    );

    let model = crate::providers::model_for_role("planner", &opts.config)?;
    let raw = crate::providers::complete(model, PREAMBLE, &prompt, opts, "planner")
        .await
        .map_err(|e| anyhow::anyhow!("Planner agent error: {e}"))?;

    // Parse questions and answers.
    let (questions, plan_section) = parse_questions_and_plan(&raw);

    // Ask clarifying questions one at a time and collect answers.
    let mut qa_pairs: Vec<(String, String)> = Vec::new();
    for question in &questions {
        if opts.cancel.is_cancelled() {
            return Ok(());
        }
        let answer = crate::workflows::dev::ask_user("planner", question, opts).await?;
        if !answer.trim().is_empty() {
            qa_pairs.push((question.clone(), answer));
        }
    }

    // If answers were given, re-run the planner with the enriched context.
    let final_plan = if qa_pairs.is_empty() {
        plan_section
    } else {
        let qa_block: String = qa_pairs
            .iter()
            .map(|(q, a)| format!("Q: {}\nA: {}", q, a))
            .collect::<Vec<_>>()
            .join("\n\n");

        let enriched_prompt = format!(
            "Idea: {}{}\n\n## Clarifications\n{}\n\nNow produce only the PLAN section (no more questions needed).",
            idea, context_block, qa_block
        );

        let refined = crate::providers::complete(model, PREAMBLE, &enriched_prompt, opts, "planner")
            .await
            .map_err(|e| anyhow::anyhow!("Planner refinement error: {e}"))?;

        extract_plan_section(&refined).unwrap_or(refined)
    };

    // Build full PLAN.md content.
    let mut plan_md = format!("# Implementation Plan\n\n**Idea:** {}\n\n", idea);
    if !qa_pairs.is_empty() {
        plan_md.push_str("## Clarifications\n\n");
        for (q, a) in &qa_pairs {
            plan_md.push_str(&format!("**Q:** {}\n**A:** {}\n\n", q, a));
        }
    }
    plan_md.push_str(&final_plan);
    plan_md.push_str("\n\n---\n*Generated by Cortex Planner — type `/approve` to execute.*\n");

    // Write PLAN.md.
    let plan_path = opts.project_dir.join("PLAN.md");
    std::fs::create_dir_all(&opts.project_dir)?;
    std::fs::write(&plan_path, &plan_md)?;

    send_agent_summary(opts, "planner", &final_plan);

    let _ = opts.tx.send(TuiEvent::AgentDone {
        agent: "planner".into(),
    });

    let _ = opts.tx.send(TuiEvent::PlanGenerated {
        path: plan_path.display().to_string(),
    });

    let _ = opts.tx.send(TuiEvent::TokenChunk {
        agent: "orchestrator".into(),
        chunk: format!(
            "Plan written to: {}\nType /approve to execute the workflow.",
            plan_path.display()
        ),
    });

    Ok(())
}

/// Splits the LLM output into `(questions, plan_text)`.
fn parse_questions_and_plan(output: &str) -> (Vec<String>, String) {
    let mut questions = Vec::new();
    let mut in_questions = false;
    let mut plan_lines: Vec<&str> = Vec::new();
    let mut in_plan = false;

    for line in output.lines() {
        let trimmed = line.trim();

        if trimmed.eq_ignore_ascii_case("questions:") || trimmed.starts_with("QUESTIONS:") {
            in_questions = true;
            in_plan = false;
            continue;
        }

        if trimmed.eq_ignore_ascii_case("plan:") || trimmed.starts_with("PLAN:") {
            in_plan = true;
            in_questions = false;
            continue;
        }

        if in_questions {
            // Lines like "- Q1: some question" or "- some question"
            if let Some(q) = trimmed
                .strip_prefix("- Q1: ")
                .or_else(|| trimmed.strip_prefix("- Q2: "))
                .or_else(|| trimmed.strip_prefix("- Q3: "))
                .or_else(|| trimmed.strip_prefix("- "))
            {
                if !q.is_empty() {
                    questions.push(q.to_string());
                }
            }
        } else if in_plan {
            plan_lines.push(line);
        }
    }

    let plan_text = if plan_lines.is_empty() {
        // Fallback: if no PLAN section found, use the whole output.
        output.to_string()
    } else {
        plan_lines.join("\n")
    };

    (questions, plan_text)
}

/// Extract only the PLAN section from a response that may start with PLAN:.
fn extract_plan_section(output: &str) -> Option<String> {
    let mut lines = output.lines();
    // Find the PLAN: marker.
    let plan_start = lines.by_ref().position(|l| {
        let t = l.trim();
        t.eq_ignore_ascii_case("plan:") || t.starts_with("PLAN:")
    })?;
    Some(output.lines().skip(plan_start + 1).collect::<Vec<_>>().join("\n"))
}
