#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProviderKind {
    Hosted,
    Aggregator,
    Local,
    Custom,
}

#[derive(Debug, Clone, Copy)]
pub struct ProviderInfo {
    pub id: &'static str,
    pub name: &'static str,
    pub env_var: Option<&'static str>,
    pub kind: ProviderKind,
    pub needs_key: bool,
    pub direct_auth: bool,
    pub description: &'static str,
}

pub const BUILTIN_PROVIDERS: &[ProviderInfo] = &[
    ProviderInfo {
        id: "openai",
        name: "OpenAI",
        env_var: Some("OPENAI_API_KEY"),
        kind: ProviderKind::Hosted,
        needs_key: true,
        direct_auth: true,
        description: "API key required; ChatGPT Plus/Pro is separate from API billing",
    },
    ProviderInfo {
        id: "openai_chatgpt",
        name: "OpenAI ChatGPT Plus/Pro",
        env_var: None,
        kind: ProviderKind::Hosted,
        needs_key: true,
        direct_auth: true,
        description: "ChatGPT subscription OAuth for Codex backend",
    },
    ProviderInfo {
        id: "anthropic",
        name: "Anthropic",
        env_var: Some("ANTHROPIC_API_KEY"),
        kind: ProviderKind::Hosted,
        needs_key: true,
        direct_auth: false,
        description: "API key required",
    },
    ProviderInfo {
        id: "gemini",
        name: "Google Gemini",
        env_var: Some("GEMINI_API_KEY"),
        kind: ProviderKind::Hosted,
        needs_key: true,
        direct_auth: false,
        description: "API key required",
    },
    ProviderInfo {
        id: "mistral",
        name: "Mistral AI",
        env_var: Some("MISTRAL_API_KEY"),
        kind: ProviderKind::Hosted,
        needs_key: true,
        direct_auth: false,
        description: "API key required",
    },
    ProviderInfo {
        id: "deepseek",
        name: "DeepSeek",
        env_var: Some("DEEPSEEK_API_KEY"),
        kind: ProviderKind::Hosted,
        needs_key: true,
        direct_auth: false,
        description: "API key required",
    },
    ProviderInfo {
        id: "xai",
        name: "xAI",
        env_var: Some("XAI_API_KEY"),
        kind: ProviderKind::Hosted,
        needs_key: true,
        direct_auth: false,
        description: "API key required",
    },
    ProviderInfo {
        id: "cohere",
        name: "Cohere",
        env_var: Some("COHERE_API_KEY"),
        kind: ProviderKind::Hosted,
        needs_key: true,
        direct_auth: false,
        description: "API key required",
    },
    ProviderInfo {
        id: "perplexity",
        name: "Perplexity",
        env_var: Some("PERPLEXITY_API_KEY"),
        kind: ProviderKind::Hosted,
        needs_key: true,
        direct_auth: false,
        description: "API key required",
    },
    ProviderInfo {
        id: "huggingface",
        name: "Hugging Face",
        env_var: Some("HUGGINGFACE_API_KEY"),
        kind: ProviderKind::Hosted,
        needs_key: true,
        direct_auth: false,
        description: "Inference Providers token required",
    },
    ProviderInfo {
        id: "azure_openai",
        name: "Azure OpenAI",
        env_var: Some("AZURE_OPENAI_API_KEY"),
        kind: ProviderKind::Hosted,
        needs_key: true,
        direct_auth: false,
        description: "API key plus AZURE_OPENAI_ENDPOINT",
    },
    ProviderInfo {
        id: "github_copilot",
        name: "GitHub Copilot",
        env_var: Some("GITHUB_COPILOT_TOKEN"),
        kind: ProviderKind::Hosted,
        needs_key: true,
        direct_auth: true,
        description: "device login; uses a Copilot subscription",
    },
    ProviderInfo {
        id: "gitlab_duo",
        name: "GitLab Duo",
        env_var: Some("GITLAB_TOKEN"),
        kind: ProviderKind::Hosted,
        needs_key: true,
        direct_auth: true,
        description: "OAuth/PAT for GitLab Duo compatible accounts",
    },
    ProviderInfo {
        id: "google_vertex",
        name: "Google Vertex AI",
        env_var: None,
        kind: ProviderKind::Hosted,
        needs_key: true,
        direct_auth: true,
        description: "gcloud Application Default Credentials",
    },
    ProviderInfo {
        id: "amazon_bedrock",
        name: "Amazon Bedrock",
        env_var: None,
        kind: ProviderKind::Hosted,
        needs_key: true,
        direct_auth: true,
        description: "AWS credential chain",
    },
    ProviderInfo {
        id: "fireworks",
        name: "Fireworks AI",
        env_var: Some("FIREWORKS_API_KEY"),
        kind: ProviderKind::Hosted,
        needs_key: true,
        direct_auth: false,
        description: "API key required",
    },
    ProviderInfo {
        id: "deepinfra",
        name: "DeepInfra",
        env_var: Some("DEEPINFRA_API_KEY"),
        kind: ProviderKind::Hosted,
        needs_key: true,
        direct_auth: false,
        description: "OpenAI-compatible API key",
    },
    ProviderInfo {
        id: "cerebras",
        name: "Cerebras",
        env_var: Some("CEREBRAS_API_KEY"),
        kind: ProviderKind::Hosted,
        needs_key: true,
        direct_auth: false,
        description: "API key required",
    },
    ProviderInfo {
        id: "moonshot",
        name: "Moonshot AI",
        env_var: Some("MOONSHOT_API_KEY"),
        kind: ProviderKind::Hosted,
        needs_key: true,
        direct_auth: false,
        description: "OpenAI-compatible API key",
    },
    ProviderInfo {
        id: "zai",
        name: "Z.ai",
        env_var: Some("ZAI_API_KEY"),
        kind: ProviderKind::Hosted,
        needs_key: true,
        direct_auth: false,
        description: "OpenAI-compatible API key",
    },
    ProviderInfo {
        id: "openrouter",
        name: "OpenRouter",
        env_var: Some("OPENROUTER_API_KEY"),
        kind: ProviderKind::Aggregator,
        needs_key: true,
        direct_auth: false,
        description: "API key required; many hosted models",
    },
    ProviderInfo {
        id: "groq",
        name: "Groq",
        env_var: Some("GROQ_API_KEY"),
        kind: ProviderKind::Aggregator,
        needs_key: true,
        direct_auth: false,
        description: "API key required; fast inference",
    },
    ProviderInfo {
        id: "together",
        name: "Together AI",
        env_var: Some("TOGETHER_API_KEY"),
        kind: ProviderKind::Aggregator,
        needs_key: true,
        direct_auth: false,
        description: "API key required",
    },
    ProviderInfo {
        id: "302ai",
        name: "302.AI",
        env_var: Some("THREE_ZERO_TWO_AI_API_KEY"),
        kind: ProviderKind::Aggregator,
        needs_key: true,
        direct_auth: false,
        description: "OpenAI-compatible API key",
    },
    ProviderInfo {
        id: "alibaba",
        name: "Alibaba Cloud",
        env_var: Some("ALIBABA_API_KEY"),
        kind: ProviderKind::Aggregator,
        needs_key: true,
        direct_auth: false,
        description: "API key required",
    },
    ProviderInfo {
        id: "cloudflare",
        name: "Cloudflare Workers AI",
        env_var: Some("CLOUDFLARE_API_KEY"),
        kind: ProviderKind::Aggregator,
        needs_key: true,
        direct_auth: false,
        description: "API key and account endpoint required",
    },
    ProviderInfo {
        id: "minimax",
        name: "MiniMax",
        env_var: Some("MINIMAX_API_KEY"),
        kind: ProviderKind::Aggregator,
        needs_key: true,
        direct_auth: false,
        description: "API key required",
    },
    ProviderInfo {
        id: "nebius",
        name: "Nebius AI Studio",
        env_var: Some("NEBIUS_API_KEY"),
        kind: ProviderKind::Aggregator,
        needs_key: true,
        direct_auth: false,
        description: "OpenAI-compatible API key",
    },
    ProviderInfo {
        id: "scaleway",
        name: "Scaleway",
        env_var: Some("SCALEWAY_API_KEY"),
        kind: ProviderKind::Aggregator,
        needs_key: true,
        direct_auth: false,
        description: "OpenAI-compatible API key",
    },
    ProviderInfo {
        id: "vercel_ai_gateway",
        name: "Vercel AI Gateway",
        env_var: Some("VERCEL_AI_GATEWAY_API_KEY"),
        kind: ProviderKind::Aggregator,
        needs_key: true,
        direct_auth: false,
        description: "API key required",
    },
    ProviderInfo {
        id: "ollama",
        name: "Ollama",
        env_var: None,
        kind: ProviderKind::Local,
        needs_key: false,
        direct_auth: false,
        description: "local Ollama server",
    },
    ProviderInfo {
        id: "lmstudio",
        name: "LM Studio",
        env_var: None,
        kind: ProviderKind::Local,
        needs_key: false,
        direct_auth: false,
        description: "local OpenAI-compatible server at 127.0.0.1:1234",
    },
];

pub fn builtin(provider: &str) -> Option<&'static ProviderInfo> {
    let provider = normalize_provider(provider);
    BUILTIN_PROVIDERS.iter().find(|info| info.id == provider)
}

pub fn normalize_provider(provider: &str) -> &str {
    match provider {
        "google" => "gemini",
        "chatgpt" | "openai-chatgpt" | "openai_codex" | "codex" => "openai_chatgpt",
        "hf" => "huggingface",
        "azure" => "azure_openai",
        "github-copilot" | "copilot" => "github_copilot",
        "gitlab-duo" | "gitlab" => "gitlab_duo",
        "google-vertex" | "vertex" | "vertex_ai" => "google_vertex",
        "amazon-bedrock" | "bedrock" | "aws_bedrock" => "amazon_bedrock",
        "vercel-ai-gateway" | "vercel" => "vercel_ai_gateway",
        "302.ai" | "302-ai" => "302ai",
        other => other,
    }
}

pub fn provider_needs_key(provider: &str) -> bool {
    builtin(provider).is_some_and(|info| info.needs_key)
}

pub fn provider_has_direct_auth(provider: &str) -> bool {
    builtin(provider).is_some_and(|info| info.direct_auth)
}

pub fn is_known_provider_prefix(provider: &str) -> bool {
    let normalized = normalize_provider(provider);
    builtin(normalized).is_some()
}
